### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by amitdalia** [saderi/freshping-telegram#1]
Hi Saderi,

Thanks for sharing the code, but can you share configuration of this in more details. I'm not a developer but just a system administrator, so doesn't know what and how to configure the same.

Thanks & Regards,

Amit

**Comment by saderi** [comment]
I have written in README.md. 
What part of the readme do you not understand?

**Comment by amitdalia** [comment]
I was confused, which file to provide in webhook. But I think, I got it now.
Webhook URL will be: http://mydomainname/webhook/hook.php

Pls Correct me if I'm wrong.

**Comment by amitdalia** [comment]
Also need to know can I put this on shared hosting server? I had run composer install on my laptop and then uploaded all the files through FTP.

**Comment by saderi** [comment]
> I was confused, which file to provide in webhook. But I think, I got it now.
> Webhook URL will be: http://mydomainname/webhook/hook.php
> 
> Pls Correct me if I'm wrong.

If you uploaded in **webhook** folder that url is correct



> Also need to know can I put this on shared hosting server? I had run composer install on my laptop and then uploaded all the files through FTP.

Yes you can use it in shared host as I use ;)

**Comment by amitdalia** [comment]
Thanks saderi, its working perfectly :)
